services:
  mysubversion:
    container_name: svn-ssh
    image: jcrespoc311/svn-ssh:latest
    build:
      context: build
      args:
        SVN_UID: ${SVN_UID:-1001}
        SVN_GID: ${SVN_GID:-1001}
    ports:
      - "0.0.0.0:${SSH_PORT:-65022}:${SSH_PORT:-65022}"
      # avoid exposing native port to the network
      - "127.0.0.1:${SVN_PORT:-3690}:${SVN_PORT:-3690}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "2"
    volumes:
      - svn-homes:/home
      - svn-root:/var/svn
    environment:
      SVN_UID: ${SVN_UID:-1001}
      SVN_GID: ${SVN_GID:-1001}
      SSH_PORT: ${SSH_PORT:-22}
      SVN_PORT: ${SVN_PORT:-3690}
      START_NATIVE: ${START_NATIVE:-}

volumes:
  svn-homes:
    external: true
  svn-root:
    external: true
